import { MALAnimeData, MALEpisode } from "@/types/anime";

export const anime_set_data: MALAnimeData = {
  mal_id: 51498,
  url: "https://myanimelist.net/anime/51498/Masamune-kun_no_Revenge_R",
  images: {
    jpg: {
      image_url: "https://cdn.myanimelist.net/images/anime/1667/135587.jpg",
      small_image_url:
        "https://cdn.myanimelist.net/images/anime/1667/135587t.jpg",
      large_image_url:
        "https://cdn.myanimelist.net/images/anime/1667/135587l.jpg",
    },
    webp: {
      image_url: "https://cdn.myanimelist.net/images/anime/1667/135587.webp",
      small_image_url:
        "https://cdn.myanimelist.net/images/anime/1667/135587t.webp",
      large_image_url:
        "https://cdn.myanimelist.net/images/anime/1667/135587l.webp",
    },
  },
  trailer: {
    youtube_id: null,
    url: null,
    embed_url:
      "https://www.youtube-nocookie.com/embed/i7x4De9e8qY?enablejsapi=1&wmode=opaque&autoplay=1",
    images: {
      image_url: null,
      small_image_url: null,
      medium_image_url: null,
      large_image_url: null,
      maximum_image_url: null,
    },
  },
  approved: true,
  titles: [
    {
      type: "Default",
      title: "Masamune-kun no Revenge R",
    },
    {
      type: "Japanese",
      title: "政宗くんのリベンジR",
    },
    {
      type: "English",
      title: "Masamune-kun's Revenge R",
    },
  ],
  title: "Masamune-kun no Revenge R",
  title_english: "Masamune-kun's Revenge R",
  title_japanese: "政宗くんのリベンジR",
  title_synonyms: [],
  type: "TV",
  source: "Manga",
  episodes: 12,
  status: "Finished Airing",
  airing: false,
  aired: {
    from: "2023-07-03T00:00:00+00:00",
    to: "2023-09-18T00:00:00+00:00",
    prop: {
      from: {
        day: 3,
        month: 7,
        year: 2023,
      },
      to: {
        day: 18,
        month: 9,
        year: 2023,
      },
    },
    string: "Jul 3, 2023 to Sep 18, 2023",
  },
  duration: "23 min per ep",
  rating: "PG-13 - Teens 13 or older",
  score: 7.23,
  scored_by: 101577,
  rank: 3348,
  popularity: 1098,
  members: 250682,
  favorites: 1345,
  synopsis:
    "With the tumultuous cultural festival behind him, Masamune Makabe continues his efforts to carry out his revenge: to make the \"Cruel Princess\" Aki Adagaki deeply fall for him and then immediately dump her. As his class is going on a trip to Paris, widely known as the City of Love, Masamune has the perfect opportunity to get even for his childhood heartbreak.\n\nBefore Masamune can impress Aki, the two meet Muriel Besson, a French high school otaku who aspires to create a romantic comedy manga series. Muriel believes Masamune is the ideal model for the protagonist and asks for his help. The boy reluctantly agrees, dragging Aki along to provide inspiration for the love interest's character. But to do so, the two must show Muriel what Japanese love is like.\n\nTo make matters more complicated, Kanetsugu Gasou is masquerading as Aki's childhood friend, Masamune, to trick and use her. With mix-ups and love rivals galore, Masamune's revenge is proving to be quite the difficult task.\n\n[Written by MAL Rewrite]",
  background:
    "Masamune-kun no Revenge R was released on Blu-ray in two volumes from September 20, 2023, to October 25, 2023.",
  season: "summer",
  year: 2023,
  broadcast: {
    day: "Mondays",
    time: "21:00",
    timezone: "Asia/Tokyo",
    string: "Mondays at 21:00 (JST)",
  },
  producers: [
    {
      mal_id: 104,
      type: "anime",
      name: "Lantis",
      url: "https://myanimelist.net/anime/producer/104/Lantis",
    },
    {
      mal_id: 238,
      type: "anime",
      name: "AT-X",
      url: "https://myanimelist.net/anime/producer/238/AT-X",
    },
    {
      mal_id: 460,
      type: "anime",
      name: "KlockWorx",
      url: "https://myanimelist.net/anime/producer/460/KlockWorx",
    },
    {
      mal_id: 843,
      type: "anime",
      name: "BS Fuji",
      url: "https://myanimelist.net/anime/producer/843/BS_Fuji",
    },
    {
      mal_id: 1211,
      type: "anime",
      name: "Tokyo MX",
      url: "https://myanimelist.net/anime/producer/1211/Tokyo_MX",
    },
    {
      mal_id: 1468,
      type: "anime",
      name: "Crunchyroll",
      url: "https://myanimelist.net/anime/producer/1468/Crunchyroll",
    },
    {
      mal_id: 1582,
      type: "anime",
      name: "Ichijinsha",
      url: "https://myanimelist.net/anime/producer/1582/Ichijinsha",
    },
    {
      mal_id: 1590,
      type: "anime",
      name: "FuRyu",
      url: "https://myanimelist.net/anime/producer/1590/FuRyu",
    },
    {
      mal_id: 2031,
      type: "anime",
      name: "Lawson Entertainment",
      url: "https://myanimelist.net/anime/producer/2031/Lawson_Entertainment",
    },
    {
      mal_id: 2425,
      type: "anime",
      name: "Bandai Namco Music Live",
      url: "https://myanimelist.net/anime/producer/2425/Bandai_Namco_Music_Live",
    },
  ],
  licensors: [],
  studios: [
    {
      mal_id: 300,
      type: "anime",
      name: "SILVER LINK.",
      url: "https://myanimelist.net/anime/producer/300/SILVER_LINK",
    },
  ],
  genres: [
    {
      mal_id: 4,
      type: "anime",
      name: "Comedy",
      url: "https://myanimelist.net/anime/genre/4/Comedy",
    },
    {
      mal_id: 22,
      type: "anime",
      name: "Romance",
      url: "https://myanimelist.net/anime/genre/22/Romance",
    },
  ],
  explicit_genres: [],
  themes: [
    {
      mal_id: 35,
      type: "anime",
      name: "Harem",
      url: "https://myanimelist.net/anime/genre/35/Harem",
    },
    {
      mal_id: 23,
      type: "anime",
      name: "School",
      url: "https://myanimelist.net/anime/genre/23/School",
    },
  ],
  demographics: [
    {
      mal_id: 27,
      type: "anime",
      name: "Shounen",
      url: "https://myanimelist.net/anime/genre/27/Shounen",
    },
  ],
};

export const anime_episode_data: MALEpisode[] = [
  {
    mal_id: 1,
    url: "https://myanimelist.net/anime/51498/Masamune-kun_no_Revenge_R/episode/1",
    title: "The Wee Parisian Mademoiselle",
    title_japanese: "巴里とオがつくマドモアゼル",
    title_romanji: "Paris to O ga Tsuku Mademoiselle ",
    aired: "2023-07-03T00:00:00+00:00",
    score: 3.87,
    filler: false,
    recap: false,
    forum_url: "https://myanimelist.net/forum/?topicid=2103847",
    synopsis:
      "Masamune and Aki's class goes to France for their school trip and there, they meet an aspiring manga artist named Muriel. (Source: Crunchyroll)",
  },
  {
    mal_id: 2,
    url: "https://myanimelist.net/anime/51498/Masamune-kun_no_Revenge_R/episode/2",
    title: "The Princess's Confession",
    title_japanese: "プリンセスの告白",
    title_romanji: "Princess no Kokuhaku ",
    aired: "2023-07-10T00:00:00+00:00",
    score: 4.16,
    filler: false,
    recap: false,
    forum_url: "https://myanimelist.net/forum/?topicid=2105302",
  },
  {
    mal_id: 3,
    url: null,
    title: "They Show Up When You Least Expect It",
    title_japanese: "忘れたころにやってくる",
    title_romanji: "Wasureta Koro ni Yatte Kuru ",
    aired: "2023-07-17T00:00:00+00:00",
    score: 4.19,
    filler: false,
    recap: false,
    forum_url: "https://myanimelist.net/forum/?topicid=2106814",
  },
  {
    mal_id: 4,
    url: null,
    title: "I'm Not Going to Fall in Love with You, Pig's Foot",
    title_japanese: "あんたなんか好きにならないわよ, 豚足",
    title_romanji: "Anta Nanka Suki ni Naranai wa yo, Tonsoku ",
    aired: "2023-07-24T00:00:00+00:00",
    score: 4.41,
    filler: false,
    recap: false,
    forum_url: "https://myanimelist.net/forum/?topicid=2108167",
  },
  {
    mal_id: 5,
    url: null,
    title: "So We Became a Couple",
    title_japanese: "彼と, 彼女になりまして",
    title_romanji: "Kare to, Kanojo ni Narimashita ",
    aired: "2023-07-31T00:00:00+00:00",
    score: 4.23,
    filler: false,
    recap: false,
    forum_url: "https://myanimelist.net/forum/?topicid=2109521",
  },
  {
    mal_id: 6,
    url: null,
    title: "Our Second Date",
    title_japanese: "二度目のデート",
    title_romanji: "Nidome no Date ",
    aired: "2023-08-07T00:00:00+00:00",
    score: 4.32,
    filler: false,
    recap: false,
    forum_url: "https://myanimelist.net/forum/?topicid=2110745",
  },
  {
    mal_id: 7,
    url: null,
    title: "There's No Point in This Confession",
    title_japanese: "言うても詮無き告白ですが",
    title_romanji: "Yuute mo Sennaki Kokuhaku Desuka ",
    aired: "2023-08-14T00:00:00+00:00",
    score: 4.09,
    filler: false,
    recap: false,
    forum_url: "https://myanimelist.net/forum/?topicid=2111925",
  },
  {
    mal_id: 8,
    url: null,
    title: "There Are Things You Shouldn't Realize",
    title_japanese: "気づいちゃいけないこともある",
    title_romanji: "Kizuicha Ikenai Koto mo Aru ",
    aired: "2023-08-21T00:00:00+00:00",
    score: 4.14,
    filler: false,
    recap: false,
    forum_url: "https://myanimelist.net/forum/?topicid=2113045",
  },
  {
    mal_id: 9,
    url: null,
    title: "Saint Valentine Is Watching",
    title_japanese: "聖バレンタインが見ている",
    title_romanji: "Sei Valentine ga Mite Iru ",
    aired: "2023-08-28T00:00:00+00:00",
    score: 4.3,
    filler: false,
    recap: false,
    forum_url: "https://myanimelist.net/forum/?topicid=2114208",
  },
  {
    mal_id: 10,
    url: null,
    title: "Whiteout",
    title_japanese: "ホワイトアウト",
    title_romanji: "Whiteout ",
    aired: "2023-09-04T00:00:00+00:00",
    score: 4.14,
    filler: false,
    recap: false,
    forum_url: "https://myanimelist.net/forum/?topicid=2115314",
  },
  {
    mal_id: 11,
    url: null,
    title: "Face Your Feelings",
    title_japanese: "自分の気持ちに向き合って",
    title_romanji: "Jibun no Kimochi ni Mukiatte ",
    aired: "2023-09-11T00:00:00+00:00",
    score: 4.19,
    filler: false,
    recap: false,
    forum_url: "https://myanimelist.net/forum/?topicid=2116477",
  },
  {
    mal_id: 12,
    url: null,
    title: "Dead or Love?",
    title_japanese: null,
    title_romanji: null,
    aired: "2023-09-18T00:00:00+00:00",
    score: 4.21,
    filler: false,
    recap: false,
    forum_url: "https://myanimelist.net/forum/?topicid=2117818",
  },
];
